image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/app
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA
  DOTNET_NUGET_SIGNATURE_VERIFICATION: "false"

build_image:
  stage: build
  script:
    # Login to GitLab Container Registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$tag" -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" -f QuoteApi/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:$tag"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

