CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Quotes" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    quote character varying(2500),
    author character varying(500),
    CONSTRAINT "PK_Quotes" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260504032000_Initial', '9.0.8');

COMMIT;

